import { Divider, Grid, StyleRulesCallback, Theme, Typography, withStyles, WithStyles } from "@material-ui/core";
import { Link } from "gatsby";
import React from "react";

const styles: StyleRulesCallback = (theme: Theme) => ({
  container: {
    padding: theme.spacing.unit * 2,
    paddingTop: theme.spacing.unit * 2,
    paddingBottom: theme.spacing.unit * 2,
  },
  headlineContainer: {
    paddingBottom: theme.spacing.unit * 2,
  },
});

interface PrivacyPolicyProps extends WithStyles<typeof styles> {}

const PrivacyPolicyComponent: React.SFC<PrivacyPolicyProps> = props => {
  return (
    <Grid container={true} justify="center" className={props.classes.container}>
      <Grid item={true} md={7} className={props.classes.headlineContainer}>
        <Typography variant="h5" align="center">
          Your privacy is our first priority. Any data you provide to us will be kept private and will not be shared
          with others.
        </Typography>
      </Grid>

      <Grid item={true} md={7} className={props.classes.headlineContainer}>
        <Divider variant="middle" />
      </Grid>

      <Grid item={true} md={7}>
        <Typography variant="h4">Privacy Policy</Typography>

        <Typography paragraph={true}>Effective date: April 07, 2019</Typography>

        <Typography paragraph={true}>
          zachaREI LLC ("us", "we", or "our") operates the https://zachareinvests.com website (hereinafter referred to
          as the "Service").
        </Typography>

        <Typography paragraph={true}>
          This page informs you of our policies regarding the collection, use, and disclosure of personal data when you
          use our Service and the choices you have associated with that data. The Privacy Policy for zachaREI LLC has
          been created with the help of{" "}
          <a href="https://termsfeed.com/privacy-policy/generator/">TermsFeed Privacy Policy Generator</a>.
        </Typography>

        <Typography paragraph={true}>
          We use your data to provide and improve the Service. By using the Service, you agree to the collection and use
          of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used
          in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from our{" "}
          <Link to="/terms">Terms and Conditions</Link>.
        </Typography>

        <Typography variant="h5">Definitions</Typography>
        <ul>
          <li>
            <Typography paragraph={true}>
              <strong>Service</strong>
            </Typography>
            <Typography paragraph={true}>
              Service is the https://zachareinvests.com website operated by zachaREI LLC
            </Typography>
          </li>
          <li>
            <Typography paragraph={true}>
              <strong>Personal Data</strong>
            </Typography>
            <Typography paragraph={true}>
              Personal Data means data about a living individual who can be identified from those data (or from those
              and other information either in our possession or likely to come into our possession).
            </Typography>
          </li>
          <li>
            <Typography paragraph={true}>
              <strong>Usage Data</strong>
            </Typography>
            <Typography paragraph={true}>
              Usage Data is data collected automatically either generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </Typography>
          </li>
          <li>
            <Typography paragraph={true}>
              <strong>Cookies</strong>
            </Typography>
            <Typography paragraph={true}>
              Cookies are small files stored on your device (computer or mobile device).
            </Typography>
          </li>
        </ul>

        <Typography variant="h5">Information Collection and Use</Typography>
        <Typography paragraph={true}>
          We collect several different types of information for various purposes to provide and improve our Service to
          you.
        </Typography>

        <Typography variant="h6">Types of Data Collected</Typography>

        <Typography variant="subtitle1">Personal Data</Typography>
        <Typography paragraph={true}>
          While using our Service, we may ask you to provide us with certain personally identifiable information that
          can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but
          is not limited to:
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
        </Typography>

        <Typography variant="subtitle1">Usage Data</Typography>

        <Typography paragraph={true}>
          We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may
          include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of your visit, the time spent on those
          pages, unique device identifiers and other diagnostic data.
        </Typography>

        {/* <Typography variant="subtitle1">Tracking & Cookies Data</Typography>
        <Typography paragraph={true}>
          We use cookies and similar tracking technologies to track the activity on our Service and we hold certain
          information.
        </Typography>
        <Typography paragraph={true}>
          Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are
          sent to your browser from a website and stored on your device. Other tracking technologies are also used such
          as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
        </Typography>
        <Typography paragraph={true}>
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if
          you do not accept cookies, you may not be able to use some portions of our Service.
        </Typography>
        <Typography paragraph={true}>
          Examples of Cookies we use:
          <ul>
            <li>Session Cookies. We use Session Cookies to operate our Service.</li>
            <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
            <li>Security Cookies. We use Security Cookies for security purposes.</li>
          </ul>
        </Typography> */}

        <Typography variant="h5">Use of Data</Typography>

        <Typography paragraph={true}>
          The data that you submit through the forms is used for determining an offer for your property. The information
          that you provide may be used to contact you about future opportunities related to selling your property. Your
          data will be kept private and will not be sold or distributed.
          <br />
          <br />
          zachaREI LLC also collects anonymous Service interaction data for various purposes:
          <ul>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide analysis or valuable information so that we can improve the Service</li>
            <li>To monitor the usage of the Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>
        </Typography>

        <Typography variant="h5">Transfer Of Data</Typography>
        <Typography paragraph={true}>
          Your information, including Personal Data, may be transferred to - and maintained on - computers located
          outside of your state, province, country or other governmental jurisdiction where the data protection laws may
          differ than those from your jurisdiction.
        </Typography>
        <Typography paragraph={true}>
          If you are located outside United States and choose to provide information to us, please note that we transfer
          the data, including Personal Data, to United States and process it there.
        </Typography>
        <Typography paragraph={true}>
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement
          to that transfer.
        </Typography>
        <Typography paragraph={true}>
          zachaREI LLC will take all steps reasonably necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization
          or a country unless there are adequate controls in place including the security of your data and other
          personal information.
        </Typography>

        <Typography variant="h5">Disclosure Of Data</Typography>

        <Typography variant="h6">Legal Requirements</Typography>
        <Typography paragraph={true}>
          zachaREI LLC may disclose your Personal Data in the good faith belief that such action is necessary to:
          <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of zachaREI LLC</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>
        </Typography>

        <Typography paragraph={true}>
          As an European citizen, under GDPR, you have certain individual rights. You can learn more about these guides
          in the <a href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR">GDPR Guide</a>.
        </Typography>

        <Typography variant="h5">Security of Data</Typography>
        <Typography paragraph={true}>
          The security of your data is important to us but remember that no method of transmission over the Internet or
          method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect
          your Personal Data, we cannot guarantee its absolute security.
        </Typography>

        <Typography variant="h5">Service Providers</Typography>
        <Typography paragraph={true}>
          We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to
          provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our
          Service is used.
        </Typography>
        <Typography paragraph={true}>
          These third parties have access to your Personal Data only to perform these tasks on our behalf and are
          obligated not to disclose or use it for any other purpose.
        </Typography>

        <Typography variant="h5">Links to Other Sites</Typography>
        <Typography paragraph={true}>
          Our Service may contain links to other sites that are not operated by us. If you click a third party link, you
          will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site
          you visit.
        </Typography>
        <Typography paragraph={true}>
          We have no control over and assume no responsibility for the content, privacy policies or practices of any
          third party sites or services.
        </Typography>

        <Typography variant="h5">Children's Privacy</Typography>
        <Typography paragraph={true}>Our Service does not address anyone under the age of 18 ("Children").</Typography>
        <Typography paragraph={true}>
          We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a
          parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If
          we become aware that we have collected Personal Data from children without verification of parental consent,
          we take steps to remove that information from our servers.
        </Typography>

        <Typography variant="h5">Changes to This Privacy Policy</Typography>
        <Typography paragraph={true}>
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page.
        </Typography>
        <Typography paragraph={true}>
          We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
          effective and update the "effective date" at the top of this Privacy Policy.
        </Typography>
        <Typography paragraph={true}>
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
          effective when they are posted on this page.
        </Typography>

        <Typography variant="h5">Contact Us</Typography>
        <Typography paragraph={true}>
          If you have any questions about this Privacy Policy, please contact us using the information on our{" "}
          <Link to="/contact">Contact Us</Link> page.
        </Typography>
      </Grid>
    </Grid>
  );
};

const PrivacyPolicy = withStyles(styles)(PrivacyPolicyComponent);
export { PrivacyPolicy };
